"""Replace legacy alert rules with employee attendance irregularity."""

from alembic import op


revision = "m1n2o3p4q5"
down_revision = "l0m1n2o3p4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Retire rule configuration but retain alerts already generated by those
    # rules as historical records.
    op.execute(
        """
        DELETE FROM alert_rules
        WHERE id IN (
            'rule-exit-balance',
            'rule-restricted-entry',
            'rule-unauthorized-hardware'
        )
           OR data ->> 'conditionKey' IN (
            'exit_balance',
            'restricted_employee_entry',
            'unauthorized_hardware_carrier'
        )
        """
    )
    op.execute(
        """
        INSERT INTO alert_rules (id, data)
        VALUES (
            'rule-irregularity',
            '{
              "id": "rule-irregularity",
              "name": "Irregularity",
              "description": "Alert when an active employee has no approved entry by the end of the day.",
              "category": "presence_anomaly",
              "severity": "medium",
              "enabled": true,
              "scope": "Employee attendance",
              "conditionKey": "irregularity",
              "recentTriggers": 0
            }'::jsonb
        )
        ON CONFLICT (id) DO NOTHING
        """
    )


def downgrade() -> None:
    # Historical alerts are untouched by this migration.
    op.execute("DELETE FROM alert_rules WHERE id = 'rule-irregularity'")
